// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTask struct {
	Content string `json:"content"`
	UserID  string `json:"userId"`
}

type NewUser struct {
	Name  string `json:"Name"`
	Email string `json:"Email"`
}
