// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccountOfUser struct {
	UserID            string `json:"userId"`
	Provider          string `json:"provider"`
	ProviderAccountID string `json:"providerAccountId"`
}

type NewSubtask struct {
	Name    string  `json:"name"`
	Content *string `json:"content"`
	TaskID  string  `json:"taskId"`
}

type NewTask struct {
	Name    string  `json:"name"`
	Content *string `json:"content"`
	UserID  string  `json:"userId"`
}

type NewUser struct {
	Name  string `json:"Name"`
	Email string `json:"Email"`
}
